informacion = ("Jhon Donoso",24,"Puerto Montt")
print("Ejercicio 1")
print(informacion.index("Jhon Donoso"))
print(informacion.index(24))
print(informacion.index("Puerto Montt"))
print()

numeros = (1,2,3,4,5,6,7,8,9,10)
print("Ejercicio 2")
print("==Sum==")
print(sum(numeros))
print()
print("==Max==")
print(max(numeros))
print()
print("==Min==")
print(min(numeros))
print()
print("==Count==")
print(numeros.count(5))
print()

letras = ("a","b","c","d","e","f","g","h","i","j")
print("Ejercicio 3")
print()
print(letras[0:5])
print()
print(letras[7:10])
print()
print(letras[1:10:2])
